services:
  - type: web
    name: my-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 22.9.0
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_FROM_EMAIL
        sync: false
      - key: BREVO_FROM_NAME
        sync: false
      - key: CLIENT_URL
        sync: false
    healthCheckPath: /health
    autoDeploy: true
